enum en_SHDB_ERROR_CODE
{
	//	default
	SUCCESS = 1,
	PARAMETERS_ERROR = -100,

	//	create.php
	ALREADY_JOIN_EMAIL = -1,
	INDEXDB_INSERT_ERROR = -2,
	DATADB_INSERT_ERROR = -3,

	//	select / update . php
	NOT_JOIN = -10,
	DATADB_ACCOUNT_NOT_EXIST = -11,
	DATADB_CONTENTS_NOT_EXIST = -12,

	// database
	INDEXDB_MASTER_CONNECT_ERROR = -50,
	INDEXDB_SLAVE_CONNECT_ERROR = -51,
	DATADB_CONNECT_ERROR = -52,
	INFODB_MASTER_CONNECT_ERROR = -53,
	INFODB_SLAVE_CONNECT_ERROR = -54,

	QUERY_ERROR = -60,
	UPDATE_COLUMN_NOT_EXIST = -61,
	UPDATE_SELECT_TABLE_NOT_EXIST = -62,
};
